config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index]
  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, :year, presence: true
    validates :live, inclusion: { in: [ true, false ] }
    belongs_to :band, dependent: :destroy
    has_many :tracks, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true
    has_many :albums, dependent: :destroy
    has_many :tracks, through: :albums
end

app/models/note.rb
class Note < ApplicationRecord
    validates :note, :track_id, :user_id, presence: :true
    belongs_to :track
    belongs_to :user
end

app/models/track.rb
class Track < ApplicationRecord
    validates :title, :album_id, :ord, presence: true
    validates :bonus, inclusion: { in: [ true, false ] }
    belongs_to :album, dependent: :destroy
    has_one :band, through: :album
    has_many :notes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    require 'bcrypt'
    validates :password, allow_nil: true, length: { minimum: 6 }
    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    has_many :notes, dependent: :destroy

    attr_reader :password

    after_initialize :ensure_session_token

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    def self.generate_session_token
        SecureRandom.urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def new
        @album = Album.new(band_id: params[:band_id])
        render :new
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to album_url(@album.id)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def show
        @album = Album.find_by(id: params[:id])
        render :show
    end

    def index
        @bands = Band.all
        render :index
    end

    def edit
        @album = Album.find_by(id: params[:id])
        render :edit
    end

    def update
        @album = Album.find_by(id: params[:id])
        if @album.update_attributes(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    private

    def album_params
        params.require(:album).permit(:title, :year, :live, :band_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :require_login

    def login_user!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout_user!
        current_user.reset_session_token!
        session[:session_token] = nil
    end

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        current_user != nil
    end

    private

    def require_login
        unless logged_in?
            flash[:error] = "You must be logged in to access this section"
            redirect_to new_session_url
        end
    end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def new
        @band = Band.new
        render :new
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def edit
        @band = Band.find_by(id: params[:id])
        render :edit
    end

    def show
        @band = Band.find_by(id: params[:id])
        render :show
    end

    def update
        @band = Band.find_by(id: params[:id])
        if @band.update_attributes(band_params)
            redirect_to band_url(@band.id)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find_by(id: params[:id])
        @band.destroy

        redirect_to bands_path
    end

    def band_params
        params.require(:band).permit(:name)
    end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    # before_action :check_id_before_deleting only: [:destroy]
    def create
        @note = current_user.notes.new(note_params)
        if @note.save
            redirect_to track_url(@note.track_id)
        else
            flash.now[:errors] = @note.errors.full_messages
        end
    end

    def destroy
        @note = current_user.notes.find_by(id: params[:id])
        @note.destroy
        redirect_to track_url(@note.track_id)
    end

    private

    def note_params
        params.require(:note).permit(:note, :track_id, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_login
    
    def create
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )

        if user.nil? 
            flash[:now] =  ["Incorrect username or password"]
            render json: "not correct"
        else
            login_user!(user)
            redirect_to user_url(user)
        end
    end

    def destroy
        logout_user!
        redirect_to new_session_url
    end

    def new
        render :new
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def new
        @track = Track.new(album_id: params[:album_id])
        render :new
    end

    def create
        @track = Track.new(track_params)
        if @track.save
            redirect_to track_path(@track)
        else
            flash.now[:errors] = @track.errors.full_messages
            render :new
        end
    end

    def show
        @track = Track.find_by(id: params[:id])
        render :show
    end

    def update
        @track = Track.find_by(id: params[:id])
        if @track.update_attributes(track_params)
            redirect_to track_path(@track)
        else
            flash.now[:errors] = @track.errors.full_messages
            render :edit
        end
    end

    def edit
        @track = Track.find_by(id: params[:id])
        render :edit
    end

    def destroy
        @track = Track.find_by(id: params[:id])
        @track.destroy
    end

    private

    def track_params
        params.require(:track).permit(:title, :lyrics, :ord, :bonus, :album_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login_user!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        render :show
    end

    private

    def user_params
        params.require(:user).permit(:password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        "<input type=hidden name=authenticity_token value=#{form_authenticity_token}/>".html_safe
    end

    def ugly_lyrics(lyrics)
        final_lyrics = ""
        lyrics.lines.each do |line|
            final_lyrics << "&#9835; #{h(line)}"
        end
        "<pre>#{final_lyrics}</pre>".html_safe
    end
end

app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>
<% button_text = album.persisted? ? "Update" : "Add" %>

<form action="<%= action_url %>" method="POST">
    <input type="hidden" name="_method" value="<%= http_method %>">
    <%= auth_token %>

    <label for="band_name">Band name</label>
    <select name="album[band_id]" id="band_name">
        <%= Band.all.each do |band| %>
        <option 
            <%= "selected" if album.band_id == band.id %> 
            value="<%= band.id %>">
            <%= band.name%>
        </option>
        <% end %>
    </select>
    <br>

    <label for="album_name">Album name</label>
    <input type="text" name=album[title] id="album_name" value="<%= album.title %>">
    <br>

    <label for="type">Type:</label>
    <input type="radio" name=album[live] id="type" value="true"> Live
    <input type="radio" name=album[live] id="type" value="false" checked> Studio
    <br>

    <label for="year">Year</label>
    <input type="number" id="year" name=album[year] value="<%= album.year %>">
    <br>


    <input type="submit" value="<%= button_text %>">
</form>

app/views/albums/edit.html.erb
<h1>Edit <%= @album.title %></h1>

<%= render 'form', album: @album %>

app/views/albums/index.html.erb
<h2> Albums </h2>

<ul>
    <% @bands.each do |band| %>
    <li>
        <%= band.name %>
        <ul>
            <% band.albums.each do |album| %>
            <li> 
                <%= link_to "#{album.title}", album_path(album.id) %>
                <% end %>
            </li>
        </ul>
    </li>
    <% end %>
</ul>

app/views/albums/new.html.erb
<h1>Submit a new album!</h1>

<%= render 'form', album: @album %>

app/views/albums/show.html.erb
<h1>
    Album name: <%= @album.title %>
</h1>

<h2>
    Recording style: <%= @album.live? ? "Live" : "Studio" %>
    <br>
    Band: <%= link_to "#{@album.band.name}", band_path(@album.band_id) %>
    <br>
    Year: <%= @album.year %>
</h2>

<%= link_to "Edit album", edit_album_path(@album) %>
<br>
<%= link_to "Delete album", album_path(@album), method: :delete, :data => {:confirm => 'Are you sure?'} %>
<br>

<h3>Tracks</h3>
<ul>
    <% @album.tracks.each do |track| %>
        <li>
            <%= link_to "#{track.title}", track_path(track.id) %>
        </li>
    <% end %>
</ul>

app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>
<% button_text = band.persisted? ? "Update" : "Add" %>


<form action="<%= action_url %>" method="POST">
    <input type="hidden" name="_method" value="<%= http_method %>">

    <%= auth_token %>

    <label for="new_name">Band name</label>
    <input type="text" name="band[name]" id="new_name" value="<%= band.name %>">


    <input type="submit" value="<%= button_text %>">
</form>

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render 'form', band: @band %>

app/views/bands/index.html.erb
<h2>Current Bands</h2>

<ul>
<% @bands.each do |band| %>
<li><%= link_to "#{band.name}", band_path(band) %></li>
<% end %>
</ul>

app/views/bands/new.html.erb
<h1>Submit a new band!</h1>

<%= render 'form', band: @band %>

app/views/bands/show.html.erb
<h1>
    <%= @band.name %>
</h1>

<%= link_to "Edit band", edit_band_path(@band) %>
<br>
<%= link_to "Delete band", band_path(@band), method: :delete, :data => {:confirm => 'Are you sure?'} %>
<br>
<h2>
    Albums
</h2>
<% @band.albums.each do |album| %>
<%= link_to "#{album.title}", album_path(album.id) %>
<br>
<% end %>
<br>

<%= link_to "New album", new_band_album_path(@band) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Notable&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="nav-bar">
      <h1 class="header">Music App!</h1>
        <ul class="nav-links"><% if current_user %>
          <h2>Welcome, <%= current_user.email %></h2>
            <li class="nav-item"><%= link_to "Logout", session_url, method: :delete %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Login", new_session_url, method: :get %></li>
          <li class="nav-item"><%= link_to "Signup", new_user_url, method: :get %></li>
        <% end %>
        </ul>
    </nav>
  </head>

  <% if flash[:errors] %>
  <%= flash[:errors].join(", ") %>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<form action="<%= notes_url %>" method="POST">
    <%= auth_token %>
    <label for="note_content"></label>
    <input type="hidden" name="note[track_id]" value="<%= track.id %>">
    <textarea name="note[note]" id="note_content" cols="30" rows="10"></textarea>
    <input type="submit" value="Submit note">
</form>

app/views/notes/_note.html.erb
<h4>Note by: <%= note.user.email %></h4>
<%= note.note %>
<% if current_user == note.user %>
    <form action="<%= note_url(note) %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <%= auth_token %>
        <input type="submit" value="Delete note">
    </form>
<% end %>

app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% http_method = track.persisted? ? "PATCH" : "POST" %>
<% button_text = track.persisted? ? "Update" : "Add" %>

<form action="<%= action_url %>" method="POST">
    <input type="hidden" name="_method" value="<%= http_method %>">

    <%= auth_token %>

    <label for="album_name">Album name</label>
    <select name="track[album_id]" id="track_name">
        <%= Album.all.each do |album| %>
        <option <%= "selected" if track.album_id == album.id %> value="<%= album.id %>">
            <%= album.title%>
        </option>
        <% end %>
    </select>
    <br>

    <label for="track_name">Track name</label>
    <input type="text" name=track[title] id="track_name" value="<%= track.title %>">
    <br>

    <label for="track_lyrics">Lyrics</label>
    <textarea name="track[lyrics]" id="track_lyrics" cols="30" rows="10"><%= track.lyrics %></textarea>
    <br>

    <label for="order">Track number:</label>
    <input type="number" name=track[ord] id="order" value="<%= track.ord %>">
    <br>

    <label for="bonus">Type</label>
    <input type="radio" name=track[bonus] id="bonus" value="true" <%= "checked" if track.bonus == true %>> Bonus
    <input type="radio" name=track[bonus] id="bonus" value="false" <%= "checked" if track.bonus == false %>> Standard
    <br>


    <input type="submit" value="<%= button_text %>">
</form>

app/views/tracks/edit.html.erb
<h1>Edit <%= @track.title %></h1>

<%= render 'form', track: @track %>

app/views/tracks/new.html.erb
<h1>Submit a new track!</h1>

<%= render 'form', track: @track %>

app/views/tracks/show.html.erb
<h1>
    <%= @track.title %> by <%= @track.band.name %>
</h1>

Lyrics: <%= ugly_lyrics(@track.lyrics) %>
<br>

<% @track.notes.each do |note| %>
    <%= render "notes/note", note: note %>
<% end %>
<br>

Add note:
<%= render "notes/form", track: @track %>
<br>

<%= link_to "Edit track", edit_track_path(@track) %>
<br>
<%= link_to "Delete track", track_path(@track), method: :delete, :data => {:confirm => 'Are you sure?'} %>
<br>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<form action="<%= users_url %>" method="POST">
    <%= auth_token %>

    <label for="user_email">Username</label>
    <input type="text" name="user[email]" id="user_email" value="<%= @user.email %>">
    <br>

    <label for="user_password">Password</label>
    <input type="text" name="user[password]" id="user_password" value="<%= @user.password %>">
    <br>

    <input type="submit" value="submit!">
</form>

app/views/users/show.html.erb
<%= current_user.attributes %>